### create aaa
POST localhost:9000/wallets/aaa

### deposit aaa
POST localhost:9000/wallets/aaa/deposit
Content-Type: application/json

{
  "amount": 50,
  "transactionId": "{{$random.uuid}}"
}

### GET balance aaa
GET localhost:9000/wallets/aaa

### create bbb
POST localhost:9000/wallets/bbb

### GET balance bbb
GET localhost:9000/wallets/bbb

### transfer
POST localhost:9000/wallets/transfer
Content-Type: application/json

{
  "amount": 25,
  "transactionId":"abc",
  "from": "aaa",
  "to": "bbb"
}

### transfer status
GET localhost:9000/transactions/abc

